[package]
name = "termite"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
serde = "1.0.217"
termion = "4.0.3"
tokio = "1.43.0"
unicode-segmentation = "1.12.0"

[[bin]]
name = "graph"
path = "./test.rs"

[[bin]]
name = "tokio"
path = "./test2.rs"
